// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header

#ifndef _Vissue_table__Syms_H_
#define _Vissue_table__Syms_H_

#include "verilated.h"

// INCLUDE MODULE CLASSES
#include "Vissue_table.h"
#include "Vissue_table___024unit.h"
#include "Vissue_table_bsg_priority_encode__W20_L1.h"
#include "Vissue_table_bsg_encode_one_hot__W7.h"

// SYMS CLASS
class Vissue_table__Syms : public VerilatedSyms {
  public:
    
    // LOCAL STATE
    const char* __Vm_namep;
    bool __Vm_activity;  ///< Used by trace routines to determine change occurred
    bool __Vm_didInit;
    
    // SUBCELL STATE
    Vissue_table*                  TOPp;
    Vissue_table_bsg_priority_encode__W20_L1 TOP__issue_table__DOT__chosen_selector;
    Vissue_table_bsg_priority_encode__W20_L1 TOP__issue_table__DOT__new_selector;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__0__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__0__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__10__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__10__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__11__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__11__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__12__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__12__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__13__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__13__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__14__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__14__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__15__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__15__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__16__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__16__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__17__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__17__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__18__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__18__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__19__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__19__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__1__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__1__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__20__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__20__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__21__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__21__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__22__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__22__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__23__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__23__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__24__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__24__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__25__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__25__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__26__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__26__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__27__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__27__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__28__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__28__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__29__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__29__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__2__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__2__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__30__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__30__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__31__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__31__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__3__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__3__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__4__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__4__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__5__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__5__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__6__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__6__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__7__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__7__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__8__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__8__KET____DOT__src_2_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__9__KET____DOT__src_1_encoder;
    Vissue_table_bsg_encode_one_hot__W7 TOP__issue_table__DOT__src_tag_match_encode__BRA__9__KET____DOT__src_2_encoder;
    
    // CREATORS
    Vissue_table__Syms(Vissue_table* topp, const char* namep);
    ~Vissue_table__Syms() {}
    
    // METHODS
    inline const char* name() { return __Vm_namep; }
    inline bool getClearActivity() { bool r=__Vm_activity; __Vm_activity=false; return r; }
    
} VL_ATTR_ALIGNED(64);

#endif // guard
