// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vissue_table.h for the primary calling header

#ifndef _Vissue_table_bsg_priority_encode__W20_L1_H_
#define _Vissue_table_bsg_priority_encode__W20_L1_H_

#include "verilated.h"

class Vissue_table__Syms;
class VerilatedVcd;

//----------

VL_MODULE(Vissue_table_bsg_priority_encode__W20_L1) {
  public:
    
    // PORTS
    VL_OUT8(addr_o,4,0);
    VL_OUT8(v_o,0,0);
    VL_IN(i,31,0);
    
    // LOCAL SIGNALS
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__addrs,7,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,5,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,3,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,3,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,5,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,3,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,3,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__left__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__addrs,1,0);
    VL_SIG8(__PVT__b__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__right__DOT__genblk1__DOT__aligned__DOT__vs,1,0);
    VL_SIG(__PVT__enc_lo,31,0);
    VL_SIG(__PVT__a__DOT__scan_lo,31,0);
    VL_SIGW(__PVT__a__DOT__scan__DOT__t,191,0,6);
    VL_SIG(__PVT__a__DOT__scan__DOT__genblk3__DOT__genblk1__DOT__scanN__DOT__row__BRA__0__KET____DOT__shifted,31,0);
    VL_SIG(__PVT__a__DOT__scan__DOT__genblk3__DOT__genblk1__DOT__scanN__DOT__row__BRA__1__KET____DOT__shifted,31,0);
    VL_SIG(__PVT__a__DOT__scan__DOT__genblk3__DOT__genblk1__DOT__scanN__DOT__row__BRA__2__KET____DOT__shifted,31,0);
    VL_SIG(__PVT__a__DOT__scan__DOT__genblk3__DOT__genblk1__DOT__scanN__DOT__row__BRA__3__KET____DOT__shifted,31,0);
    VL_SIG(__PVT__a__DOT__scan__DOT__genblk3__DOT__genblk1__DOT__scanN__DOT__row__BRA__4__KET____DOT__shifted,31,0);
    
    // LOCAL VARIABLES
    
    // INTERNAL VARIABLES
  private:
    Vissue_table__Syms* __VlSymsp;  // Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    Vissue_table_bsg_priority_encode__W20_L1& operator= (const Vissue_table_bsg_priority_encode__W20_L1&);  ///< Copying not allowed
    Vissue_table_bsg_priority_encode__W20_L1(const Vissue_table_bsg_priority_encode__W20_L1&);  ///< Copying not allowed
  public:
    Vissue_table_bsg_priority_encode__W20_L1(const char* name="TOP");
    ~Vissue_table_bsg_priority_encode__W20_L1();
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(Vissue_table__Syms* symsp, bool first);
    void _combo__TOP__issue_table__DOT__chosen_selector__9(Vissue_table__Syms* __restrict vlSymsp);
    void _combo__TOP__issue_table__DOT__new_selector__8(Vissue_table__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset();
  public:
    static void _initial__TOP__issue_table__DOT__chosen_selector__1(Vissue_table__Syms* __restrict vlSymsp);
    void _sequent__TOP__issue_table__DOT__chosen_selector__7(Vissue_table__Syms* __restrict vlSymsp);
    void _sequent__TOP__issue_table__DOT__new_selector__6(Vissue_table__Syms* __restrict vlSymsp);
    void _settle__TOP__issue_table__DOT__chosen_selector__3(Vissue_table__Syms* __restrict vlSymsp);
    void _settle__TOP__issue_table__DOT__chosen_selector__5(Vissue_table__Syms* __restrict vlSymsp);
    void _settle__TOP__issue_table__DOT__new_selector__4(Vissue_table__Syms* __restrict vlSymsp);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif // guard
